const sources = [
 ["AndroidX Tracing release notes","developer.android.com","https://developer.android.com/jetpack/androidx/releases/tracing"],
 ["Navigation 3 release notes","developer.android.com","https://developer.android.com/jetpack/androidx/releases/navigation3"],
 ["Apple platform releases","developer.apple.com","https://developer.apple.com/news/releases/"],
 ["Android developer verification rollout","android-developers.googleblog.com","https://android-developers.googleblog.com/2026/06/android-developer-verification.html"],
 ["What’s new in Kotlin EAP","kotlinlang.org","https://kotlinlang.org/docs/whatsnew-eap.html"],
 ["Compose Multiplatform releases","github.com","https://github.com/JetBrains/compose-multiplatform/releases"],
 ["React Native 0.86","reactnative.dev","https://reactnative.dev/blog/2026/06/11/react-native-0.86"],
 ["Ktor releases","ktor.io","https://ktor.io/docs/releases.html"]
];

const ui = {
ru:{
 metaTitle:"Решения недели для мобильной разработки — MAX.D / SIGNAL 002",metaDescription:"AndroidX Tracing 2.0 RC, Navigation 3, Apple 26.6 и Android developer verification: зрелость, риски и практические действия.",
 role:"Мобильный консультант · Full-stack разработчик",nav:["Услуги","Кейсы","Журнал","Форматы работы"],
 languageLabel:"Язык",themeLabel:"Сменить тему",menuLabel:"Открыть содержание",closeLabel:"Закрыть содержание",issueNo:"Выпуск / 002",decisionKicker:"Карта решений / 01",actionKicker:"План действий / 02",sourcesKicker:"Источники / 03",footerLocation:"Монтевидео, Уругвай · Работаю удалённо по всему миру",
 coverKicker:"Инженерный журнал",coverTitle:'Изменения в выпуске мобильных приложений, <span class="accent">которые требуют действий.</span>',coverDeck:"Tracing 2.0 дошёл до RC, Navigation 3 укрепляет стабильную ветку, Apple выпустила 26.6, а проверка Android-разработчиков становится частью процесса выпуска.",
 date:"3 августа 2026",read:"10 минут чтения",sourcePolicy:"В основе — англоязычные первоисточники",inIssue:"В этом выпуске",copy:"Копировать ссылку",copied:"Ссылка скопирована",print:"Печать / PDF",
 decisionHeading:"Что делать с изменениями этой недели.",leadStatus:"Пилотировать",leadTitle:"Tracing 2.0 уже можно проверять на реальных узких местах.",leadDeck:"RC связывает coroutine, repository, сеть и UI в единую временную картину — без обязательной внешней observability-платформы.",
 smallStatus1:"Использовать",smallTitle1:"Navigation 3 становится практичным выбором для новых Compose-приложений.",smallDeck1:"Stable 1.1.x делает navigation state явной частью архитектуры; миграция зрелого проекта всё ещё требует причины.",
 smallStatus2:"Проверить",smallTitle2:"Android developer verification меняет не код, а контроль над поставкой.",smallDeck2:"Нужно знать владельцев signing keys, developer identity и всех каналов установки вне Google Play.",
 openContents:"Открыть содержание",railNote:"Факты, редакционные выводы и рекомендации разделены, чтобы уровень уверенности был виден.",actionHeading:"Работа на ближайшую неделю.",sourcesHeading:"Первоисточники этого выпуска.",
 ctaTitle:"Нужно ускорить или стабилизировать мобильный продукт?",ctaCopy:"Могу взять на себя архитектуру, backend, Android и iOS, производительность или весь путь до выпуска.",ctaButton:"Обсудить проект",
 labels:["Зрелость","Решение","Влияние","Риск","Подтверждено источником","Редакционный анализ","Стоимость перехода","Вердикт","Открыть первоисточник"],
 decisions:[["Пилотировать","Добавить Tracing 2.0 RC в один performance-critical сценарий."],["Использовать","Для нового Compose-first модуля оценивать Navigation 3 stable."],["Проверить","Прогнать приложения на Apple 26.6 и зафиксировать регрессии."],["Аудировать","Инвентаризировать Android signing identity и каналы распространения."]],
 actionTitles:["Сделать","Тестировать","Наблюдать"],actions:[["Связать trace-события между coroutine, repository и UI.","Обновить Navigation 3 до 1.1.5 там, где библиотека уже используется.","Проверить production-сборки на iOS и iPadOS 26.6."],["Kotlin 2.4.20-Beta2 в отдельной KMP-ветке.","Navigation 3 для нового Compose-first модуля.","Путь установки APK вне Google Play."],["Stable-релиз Tracing 2.0.","Фактический rollout Android developer verification.","Следующие значимые Compose Multiplatform, React Native и Ktor релизы."]]
},
en:{
 metaTitle:"Mobile delivery decisions — MAX.D / SIGNAL 002",metaDescription:"AndroidX Tracing 2.0 RC, Navigation 3, Apple 26.6, and Android developer verification, with maturity, risk, and practical actions.",
 role:"Mobile consultant · Full-stack mobile app developer",nav:["Services","Case studies","Journal","Ways to work"],
 languageLabel:"Language",themeLabel:"Switch theme",menuLabel:"Open contents",closeLabel:"Close contents",issueNo:"Issue / 002",decisionKicker:"Decision board / 01",actionKicker:"Action list / 02",sourcesKicker:"Sources / 03",footerLocation:"Montevideo, Uruguay · Remote worldwide",
 coverKicker:"Engineering journal",coverTitle:'Mobile delivery changes <span class="accent">that call for action.</span>',coverDeck:"Tracing 2.0 reaches RC, Navigation 3 strengthens its stable line, Apple ships 26.6, and Android developer verification becomes a release-operations concern.",
 date:"3 August 2026",read:"10 min read",sourcePolicy:"Based on English-language primary sources",inIssue:"In this issue",copy:"Copy link",copied:"Link copied",print:"Print / PDF",
 decisionHeading:"What to do with this week’s changes.",leadStatus:"Pilot",leadTitle:"Tracing 2.0 is ready for a real bottleneck pilot.",leadDeck:"The RC can connect coroutines, repositories, network work, and UI frames into one timeline without requiring a full observability platform.",
 smallStatus1:"Use",smallTitle1:"Navigation 3 is becoming a practical default for new Compose apps.",smallDeck1:"Stable 1.1.x makes navigation state explicit; a mature application still needs a concrete reason to migrate.",
 smallStatus2:"Audit",smallTitle2:"Android developer verification changes delivery ownership, not app architecture.",smallDeck2:"Teams need a clear inventory of signing keys, developer identity, and every installation channel outside Google Play.",
 openContents:"Open contents",railNote:"Confirmed facts, editorial conclusions, and recommendations are separated so confidence stays visible.",actionHeading:"Engineering work for the coming week.",sourcesHeading:"Primary material behind this issue.",
 ctaTitle:"Need to accelerate or stabilize a mobile product?",ctaCopy:"I can own architecture, backend, Android and iOS clients, performance, or the full route to release.",ctaButton:"Discuss a project",
 labels:["Maturity","Decision","Impact","Risk","Confirmed by source","Editorial analysis","Migration cost","Verdict","Open primary source"],
 decisions:[["Pilot","Add Tracing 2.0 RC to one performance-critical flow."],["Use","Evaluate stable Navigation 3 for a new Compose-first module."],["Verify","Run production apps on Apple 26.6 and record regressions."],["Audit","Inventory Android signing identity and distribution channels."]],
 actionTitles:["Act","Test","Watch"],actions:[["Connect trace events across coroutine, repository, and UI.","Update existing Navigation 3 users to 1.1.5.","Run production builds on iOS and iPadOS 26.6."],["Kotlin 2.4.20-Beta2 in an isolated KMP branch.","Navigation 3 in a new Compose-first module.","An APK installation path outside Google Play."],["Tracing 2.0 stable.","The real Android developer verification rollout.","The next consequential Compose Multiplatform, React Native, and Ktor releases."]]
},
es:{
 metaTitle:"Decisiones de entrega mobile — MAX.D / SIGNAL 002",metaDescription:"AndroidX Tracing 2.0 RC, Navigation 3, Apple 26.6 y la verificación de desarrolladores Android: madurez, riesgos y acciones.",
 role:"Consultor de productos móviles · Desarrollador full-stack",nav:["Servicios","Casos","Revista","Formas de trabajo"],
 languageLabel:"Idioma",themeLabel:"Cambiar tema",menuLabel:"Abrir el contenido",closeLabel:"Cerrar el contenido",issueNo:"Edición / 002",decisionKicker:"Mapa de decisiones / 01",actionKicker:"Plan de acción / 02",sourcesKicker:"Fuentes / 03",footerLocation:"Montevideo, Uruguay · Trabajo remoto en todo el mundo",
 coverKicker:"Revista de ingeniería",coverTitle:'Cambios en la entrega de aplicaciones móviles <span class="accent">que exigen actuar.</span>',coverDeck:"Tracing 2.0 llega a RC, Navigation 3 consolida su línea estable, Apple publica la versión 26.6 y la verificación de desarrolladores Android pasa a formar parte de las operaciones de lanzamiento.",
 date:"3 de agosto de 2026",read:"10 min de lectura",sourcePolicy:"Basado en fuentes primarias en inglés",inIssue:"En esta edición",copy:"Copiar enlace",copied:"Enlace copiado",print:"Imprimir / PDF",
 decisionHeading:"Qué conviene hacer con los cambios de esta semana.",leadStatus:"Probar",leadTitle:"Tracing 2.0 ya merece una prueba con un cuello de botella real.",leadDeck:"La RC permite conectar coroutines, repositorios, red y frames de interfaz en una sola línea temporal sin exigir una plataforma completa de observabilidad.",
 smallStatus1:"Usar",smallTitle1:"Navigation 3 se vuelve una opción práctica para nuevas apps con Compose.",smallDeck1:"La versión estable 1.1.x hace explícito el estado de navegación; una app madura sigue necesitando un motivo concreto para migrar.",
 smallStatus2:"Auditar",smallTitle2:"La verificación de desarrolladores Android cambia la propiedad del proceso de entrega.",smallDeck2:"El equipo debe conocer los dueños de las claves de firma, la identidad del desarrollador y todos los canales fuera de Google Play.",
 openContents:"Abrir el contenido",railNote:"Los hechos confirmados, las conclusiones editoriales y las recomendaciones aparecen por separado para mostrar el nivel de certeza.",actionHeading:"Trabajo de ingeniería para la próxima semana.",sourcesHeading:"Fuentes primarias de esta edición.",
 ctaTitle:"¿Necesitas acelerar o estabilizar un producto mobile?",ctaCopy:"Puedo hacerme cargo de la arquitectura, el backend, Android, iOS, el rendimiento o todo el camino hasta el lanzamiento.",ctaButton:"Hablemos del proyecto",
 labels:["Madurez","Decisión","Impacto","Riesgo","Confirmado por la fuente","Análisis editorial","Costo de migración","Veredicto","Abrir la fuente primaria"],
 decisions:[["Probar","Incorporar Tracing 2.0 RC a un flujo crítico para el rendimiento."],["Usar","Evaluar Navigation 3 estable en un módulo nuevo basado en Compose."],["Verificar","Probar las apps de producción en Apple 26.6 y registrar regresiones."],["Auditar","Inventariar la identidad de firma y los canales de distribución Android."]],
 actionTitles:["Actuar","Probar","Observar"],actions:[["Conectar eventos de tracing entre coroutine, repositorio e interfaz.","Actualizar a Navigation 3 1.1.5 donde ya se usa la biblioteca.","Probar las builds de producción en iOS y iPadOS 26.6."],["Kotlin 2.4.20-Beta2 en una rama KMP aislada.","Navigation 3 en un módulo Compose-first nuevo.","Una ruta de instalación de APK fuera de Google Play."],["La versión estable de Tracing 2.0.","El despliegue real de la verificación de desarrolladores Android.","Los próximos lanzamientos relevantes de Compose Multiplatform, React Native y Ktor."]]
},
pt:{
 metaTitle:"Decisões de entrega mobile — MAX.D / SIGNAL 002",metaDescription:"AndroidX Tracing 2.0 RC, Navigation 3, Apple 26.6 e a verificação de desenvolvedores Android: maturidade, riscos e ações.",
 role:"Consultor de produtos mobile · Desenvolvedor full-stack",nav:["Serviços","Projetos","Revista","Formas de trabalho"],
 languageLabel:"Idioma",themeLabel:"Alternar tema",menuLabel:"Abrir o conteúdo",closeLabel:"Fechar o conteúdo",issueNo:"Edição / 002",decisionKicker:"Mapa de decisões / 01",actionKicker:"Plano de ação / 02",sourcesKicker:"Fontes / 03",footerLocation:"Montevidéu, Uruguai · Trabalho remoto para o mundo todo",
 coverKicker:"Revista de engenharia",coverTitle:'Mudanças no processo de entrega mobile <span class="accent">que exigem ação.</span>',coverDeck:"Tracing 2.0 chega a RC, Navigation 3 fortalece sua linha estável, a Apple lança a versão 26.6 e a verificação de desenvolvedores Android passa a fazer parte das operações de release.",
 date:"3 de agosto de 2026",read:"10 min de leitura",sourcePolicy:"Baseado em fontes primárias em inglês",inIssue:"Nesta edição",copy:"Copiar link",copied:"Link copiado",print:"Imprimir / PDF",
 decisionHeading:"O que fazer com as mudanças desta semana.",leadStatus:"Testar",leadTitle:"Tracing 2.0 já merece um piloto em um gargalo real.",leadDeck:"A RC permite conectar coroutines, repositórios, rede e frames da interface em uma única linha do tempo sem exigir uma plataforma completa de observabilidade.",
 smallStatus1:"Usar",smallTitle1:"Navigation 3 está se tornando uma opção prática para novos apps em Compose.",smallDeck1:"A versão estável 1.1.x torna explícito o estado de navegação; um app maduro ainda precisa de um motivo concreto para migrar.",
 smallStatus2:"Auditar",smallTitle2:"A verificação de desenvolvedores Android muda a responsabilidade pela entrega.",smallDeck2:"A equipe precisa conhecer os donos das chaves de assinatura, a identidade do desenvolvedor e todos os canais fora da Google Play.",
 openContents:"Abrir o conteúdo",railNote:"Fatos confirmados, conclusões editoriais e recomendações aparecem separados para deixar claro o grau de certeza.",actionHeading:"Trabalho de engenharia para a próxima semana.",sourcesHeading:"Fontes primárias desta edição.",
 ctaTitle:"Precisa acelerar ou estabilizar um produto mobile?",ctaCopy:"Posso assumir arquitetura, backend, Android, iOS, performance ou todo o caminho até o lançamento.",ctaButton:"Conversar sobre o projeto",
 labels:["Maturidade","Decisão","Impacto","Risco","Confirmado pela fonte","Análise editorial","Custo de migração","Veredito","Abrir a fonte primária"],
 decisions:[["Testar","Adicionar Tracing 2.0 RC a um fluxo crítico para a performance."],["Usar","Avaliar Navigation 3 estável em um novo módulo Compose-first."],["Verificar","Rodar os apps de produção no Apple 26.6 e registrar regressões."],["Auditar","Inventariar identidade de assinatura e canais de distribuição Android."]],
 actionTitles:["Agir","Testar","Acompanhar"],actions:[["Conectar eventos de tracing entre coroutine, repositório e interface.","Atualizar para Navigation 3 1.1.5 onde a biblioteca já é usada.","Testar builds de produção no iOS e iPadOS 26.6."],["Kotlin 2.4.20-Beta2 em uma branch KMP isolada.","Navigation 3 em um novo módulo Compose-first.","Um caminho de instalação de APK fora da Google Play."],["A versão estável do Tracing 2.0.","O rollout real da verificação de desenvolvedores Android.","Os próximos lançamentos relevantes de Compose Multiplatform, React Native e Ktor."]]
}
};

const articleCore = [
{
 topic:["AndroidX Tracing","AndroidX Tracing","AndroidX Tracing","AndroidX Tracing"],status:["Пилотировать","Pilot","Probar","Testar"],
 title:["AndroidX Tracing 2.0 вышел в RC.","AndroidX Tracing 2.0 reaches RC.","AndroidX Tracing 2.0 llega a RC.","AndroidX Tracing 2.0 chega a RC."],
 lead:["Инструмент уже достаточно зрелый для ограниченного внедрения в критичных для производительности сценариях.","The tool is mature enough for a limited rollout in performance-critical flows.","La herramienta ya es suficientemente madura para una adopción limitada en flujos críticos para el rendimiento.","A ferramenta já está madura o bastante para uma adoção limitada em fluxos críticos para a performance."],
 meta:[["RC","Пилотировать","Производительность · наблюдаемость","Средний"],["RC","Pilot","Performance · observability","Medium"],["RC","Probar","Rendimiento · observabilidad","Medio"],["RC","Testar","Performance · observabilidade","Médio"]],
 confirmed:["29 июля вышел androidx.tracing:tracing-*:2.0.0-rc01. Ветка 2.0 добавляет внутрипроцессную трассировку, propagation tokens, Perfetto flows и объединение app trace с системным Perfetto trace.","androidx.tracing:tracing-*:2.0.0-rc01 shipped on July 29. The 2.0 line adds in-process tracing, propagation tokens, Perfetto flows, and the ability to merge app traces with a system Perfetto trace.","androidx.tracing:tracing-*:2.0.0-rc01 se publicó el 29 de julio. La línea 2.0 añade tracing dentro del proceso, tokens de propagación, flujos de Perfetto y la unión de trazas de la app con una traza del sistema.","androidx.tracing:tracing-*:2.0.0-rc01 foi lançado em 29 de julho. A linha 2.0 adiciona tracing no processo, tokens de propagação, fluxos do Perfetto e a união de traces do app com o trace do sistema."],
 body:[["Обычные логи фиксируют события, но плохо показывают временную причинность между действием пользователя, coroutine, repository, сетью и кадром Compose.","Главный риск — построить тяжёлый внутренний tracing framework до стабилизации API."],["Logs record events but poorly explain timing causality across a user action, coroutine, repository, network work, and a Compose frame.","The main risk is building a heavy internal tracing framework before the API stabilizes."],["Los logs registran eventos, pero explican mal la causalidad temporal entre una acción, una coroutine, el repositorio, la red y un frame de Compose.","El mayor riesgo es construir un framework interno complejo antes de que el API se estabilice."],["Logs registram eventos, mas explicam mal a causalidade temporal entre uma ação, uma coroutine, o repositório, a rede e um frame do Compose.","O maior risco é criar um framework interno pesado antes da estabilização da API."]],
 analysis:["Одна качественная трасса cold start, media, карт, BLE или geofencing может дать больше, чем десятки разрозненных логов.","One strong trace for cold start, media, maps, BLE, or geofencing can be more useful than dozens of disconnected logs.","Una buena traza del inicio, multimedia, mapas, BLE o geofencing puede aportar más que decenas de logs aislados.","Um bom trace de inicialização, mídia, mapas, BLE ou geofencing pode trazer mais valor que dezenas de logs isolados."],
 migration:[["Изменения кода","Средние","API-риск","Средний"],["Code changes","Medium","API risk","Medium"],["Cambios de código","Medios","Riesgo API","Medio"],["Mudanças de código","Médias","Risco API","Médio"]],
 verdict:["Выбрать один тяжёлый flow и связать trace-события между слоями. Пока не оборачивать каждую функцию.","Choose one expensive flow and connect trace events across layers. Do not wrap every function yet.","Elegir un flujo costoso y conectar eventos entre capas. Todavía no conviene envolver cada función.","Escolher um fluxo pesado e conectar eventos entre as camadas. Ainda não vale envolver cada função."],source:0
},
{
 topic:["Navigation 3","Navigation 3","Navigation 3","Navigation 3"],status:["Использовать","Use","Usar","Usar"],
 title:["Navigation 3 укрепляется как Compose-first архитектура.","Navigation 3 is settling in as a Compose-first architecture.","Navigation 3 se consolida como arquitectura Compose-first.","Navigation 3 se consolida como arquitetura Compose-first."],
 lead:["Stable 1.1.5 исправляет приоритет entryProvider, а 1.2 alpha продолжает развивать будущие возможности.","Stable 1.1.5 fixes entryProvider precedence while the 1.2 alpha line continues to explore future capabilities.","La versión estable 1.1.5 corrige la prioridad de entryProvider, mientras la línea 1.2 alpha explora funciones futuras.","A versão estável 1.1.5 corrige a prioridade de entryProvider, enquanto a linha 1.2 alpha explora recursos futuros."],
 meta:[["Stable · Alpha","Использовать выборочно","Архитектура · состояние","Средний"],["Stable · Alpha","Use selectively","Architecture · state","Medium"],["Estable · Alpha","Uso selectivo","Arquitectura · estado","Medio"],["Estável · Alpha","Uso seletivo","Arquitetura · estado","Médio"]],
 confirmed:["29 июля вышли Navigation 3 1.1.5 и 1.2.0-alpha07. Stable-патч исправляет выбор более конкретной записи в entryProvider DSL.","Navigation 3 1.1.5 and 1.2.0-alpha07 shipped on July 29. The stable patch fixes selection of the more specific entry in the entryProvider DSL.","Navigation 3 1.1.5 y 1.2.0-alpha07 se publicaron el 29 de julio. El parche estable corrige la selección de la entrada más específica en el DSL entryProvider.","Navigation 3 1.1.5 e 1.2.0-alpha07 foram lançados em 29 de julho. O patch estável corrige a seleção da entrada mais específica no DSL entryProvider."],
 body:[["Navigation state принадлежит приложению и передаётся в NavDisplay. Это хорошо сочетается с unidirectional data flow, typed keys, multi-pane UI и тестами без NavController.","Полная миграция зрелого приложения требует пересмотра deep links, nested graphs, state restoration, аналитики и внешних intents."],["The app owns navigation state and passes it to NavDisplay. That fits unidirectional data flow, typed keys, multi-pane UI, and tests without a NavController.","A full migration of a mature app still touches deep links, nested graphs, state restoration, analytics, and external intents."],["La app es dueña del estado de navegación y lo entrega a NavDisplay. Esto encaja con flujo unidireccional, claves tipadas, interfaces multipanel y pruebas sin NavController.","Migrar una app madura implica revisar deep links, grafos anidados, restauración de estado, analítica e intents externos."],["O app é dono do estado de navegação e o passa ao NavDisplay. Isso combina com fluxo unidirecional, chaves tipadas, UI multipainel e testes sem NavController.","Migrar um app maduro exige revisar deep links, grafos aninhados, restauração de estado, analytics e intents externos."]],
 analysis:["Для нового Compose-first приложения модель уже практична. Для существующего проекта сама новизна библиотеки не является причиной миграции.","The model is practical for a new Compose-first app. Novelty alone is not a reason to migrate an existing product.","El modelo ya es práctico para una app nueva basada en Compose. La novedad no basta para justificar una migración.","O modelo já é prático para um novo app em Compose. A novidade não é motivo suficiente para migrar um produto existente."],
 migration:[["Новый проект","Низкие","Зрелое приложение","Высокие"],["New project","Low","Mature app","High"],["Proyecto nuevo","Bajo","App madura","Alto"],["Projeto novo","Baixo","App maduro","Alto"]],
 verdict:["Для нового приложения использовать stable 1.1.x. Зрелый проект мигрировать только при конкретной боли.","Use stable 1.1.x for a new app. Migrate a mature product only to solve a concrete problem.","Usar la línea estable 1.1.x en proyectos nuevos. Migrar una app madura solo para resolver un problema concreto.","Usar a linha estável 1.1.x em projetos novos. Migrar um app maduro apenas para resolver um problema concreto."],source:1
},
{
 topic:["Apple platforms","Apple platforms","Plataformas Apple","Plataformas Apple"],status:["Проверить","Verify","Verificar","Verificar"],
 title:["Apple выпустила iOS, iPadOS и macOS 26.6.","Apple ships iOS, iPadOS, and macOS 26.6.","Apple publica iOS, iPadOS y macOS 26.6.","A Apple lança iOS, iPadOS e macOS 26.6."],
 lead:["Нужен обычный регрессионный прогон production-приложений, но архитектурной реакции не требуется.","Production apps need a normal regression pass, not an architectural reaction.","Las apps de producción necesitan una regresión normal, no una reacción arquitectónica.","Apps de produção precisam de uma regressão normal, não de uma reação arquitetural."],
 meta:[["Stable OS","Проверить","Совместимость · поставка","Низкий"],["Stable OS","Verify","Compatibility · delivery","Low"],["SO estable","Verificar","Compatibilidad · entrega","Bajo"],["SO estável","Verificar","Compatibilidade · entrega","Baixo"]],
 confirmed:["27 июля Apple выпустила iOS 26.6, iPadOS 26.6 и macOS 26.6. Xcode 27 остаётся в beta-линейке.","Apple released iOS 26.6, iPadOS 26.6, and macOS 26.6 on July 27. Xcode 27 remains on its beta line.","Apple publicó iOS 26.6, iPadOS 26.6 y macOS 26.6 el 27 de julio. Xcode 27 sigue en beta.","A Apple lançou iOS 26.6, iPadOS 26.6 e macOS 26.6 em 27 de julho. O Xcode 27 continua em beta."],
 body:[["Минимальный набор: push, universal links, background tasks, location, camera, Keychain, networking, keyboard, StoreKit и platform interop.","Для KMP отдельно проверить lifecycle shared-кода, Darwin networking, Kotlin/Swift callbacks и Compose rendering после background/foreground."],["The minimum set covers push, universal links, background tasks, location, camera, Keychain, networking, keyboard, StoreKit, and platform interop.","For KMP, also verify shared-code lifecycle, Darwin networking, Kotlin/Swift callbacks, and Compose rendering across background and foreground."],["El conjunto mínimo incluye push, universal links, tareas en background, ubicación, cámara, Keychain, red, teclado, StoreKit e interoperabilidad.","En KMP también hay que revisar el ciclo de vida compartido, Darwin networking, callbacks Kotlin/Swift y el rendering de Compose al volver del background."],["O conjunto mínimo inclui push, universal links, tarefas em background, localização, câmera, Keychain, rede, teclado, StoreKit e interoperabilidade.","Em KMP, também vale revisar o ciclo de vida compartilhado, Darwin networking, callbacks Kotlin/Swift e o rendering do Compose ao voltar do background."]],
 analysis:["Важно не путать стабильную ОС с beta toolchain: production-сборка на Xcode 27 без необходимости добавляет риск.","Do not confuse a stable OS with a beta toolchain: building production on Xcode 27 without a need adds risk.","No hay que confundir un SO estable con un toolchain beta: compilar producción con Xcode 27 sin necesidad añade riesgo.","Não confundir um SO estável com um toolchain beta: compilar produção no Xcode 27 sem necessidade adiciona risco."],
 migration:[["Изменения кода","Обычно нет","Регрессионный риск","Низкий"],["Code changes","Usually none","Regression risk","Low"],["Cambios de código","Normalmente ninguno","Riesgo de regresión","Bajo"],["Mudanças de código","Normalmente nenhuma","Risco de regressão","Baixo"]],
 verdict:["Прогнать приложения на 26.6. Сохранять стабильный release toolchain, пока нет причины менять его.","Run apps on 26.6. Keep the stable release toolchain until there is a reason to change it.","Probar las apps en 26.6. Mantener el toolchain estable hasta que exista un motivo para cambiarlo.","Testar os apps na versão 26.6. Manter o toolchain estável até existir um motivo para mudar."],source:2
},
{
 topic:["Android delivery","Android delivery","Entrega Android","Entrega Android"],status:["Аудировать","Audit","Auditar","Auditar"],
 title:["Android developer verification переходит в практическую фазу.","Android developer verification enters its practical phase.","La verificación de desarrolladores Android entra en su fase práctica.","A verificação de desenvolvedores Android entra na fase prática."],
 lead:["Августовский этап затрагивает sideloading, signing identity и процессы передачи контроля над релизами.","The August phase affects sideloading, signing identity, and control-transfer procedures for releases.","La etapa de agosto afecta el sideloading, la identidad de firma y la transferencia de control sobre los lanzamientos.","A etapa de agosto afeta sideloading, identidade de assinatura e transferência de controle sobre releases."],
 meta:[["Подтверждено","Аудировать","Поставка · ownership","Высокий"],["Confirmed","Audit","Delivery · ownership","High"],["Confirmado","Auditar","Entrega · propiedad","Alto"],["Confirmado","Auditar","Entrega · responsabilidade","Alto"]],
 confirmed:["Google объявила глобальный запуск limited distribution accounts, Android Developer Console API и advanced flow в августе 2026 года. Региональное требование регистрации начинается 30 сентября.","Google announced a global August 2026 launch for limited distribution accounts, the Android Developer Console API, and the advanced flow. Regional registration enforcement begins September 30.","Google anunció para agosto de 2026 el lanzamiento global de cuentas de distribución limitada, la API de Android Developer Console y el flujo avanzado. La exigencia regional comienza el 30 de septiembre.","O Google anunciou para agosto de 2026 o lançamento global de contas de distribuição limitada, da API do Android Developer Console e do fluxo avançado. A exigência regional começa em 30 de setembro."],
 body:[["Особенно важны direct APK, закрытые beta, региональные магазины, client installs, companion apps и внутренние utilities.","Нужно знать владельца developer identity, signing keys, release credentials, legacy APK и процедуры emergency build."],["The affected inventory includes direct APKs, closed betas, regional stores, client installs, companion apps, and internal utilities.","Teams need named owners for developer identity, signing keys, release credentials, legacy APKs, and emergency builds."],["El inventario incluye APK directos, betas cerradas, tiendas regionales, instalaciones para clientes, companion apps y utilidades internas.","Hay que definir responsables de la identidad, claves de firma, credenciales, APK antiguos y builds de emergencia."],["O inventário inclui APKs diretos, betas fechadas, lojas regionais, instalações para clientes, companion apps e utilitários internos.","É preciso definir responsáveis pela identidade, chaves de assinatura, credenciais, APKs antigos e builds de emergência."]],
 analysis:["Для продукта только в Google Play под стабильным корпоративным аккаунтом срочность ниже, но ownership всё равно должен быть документирован.","Urgency is lower for a Play-only product under a stable corporate account, but ownership still needs documentation.","La urgencia es menor para un producto exclusivo de Google Play bajo una cuenta corporativa estable, pero la propiedad debe quedar documentada.","A urgência é menor para um produto exclusivo da Google Play sob uma conta corporativa estável, mas a responsabilidade precisa estar documentada."],
 migration:[["Изменения кода","Низкие","Операционный риск","Высокий"],["Code changes","Low","Operational risk","High"],["Cambios de código","Bajos","Riesgo operativo","Alto"],["Mudanças de código","Baixas","Risco operacional","Alto"]],
 verdict:["Сейчас провести аудит каналов установки и владельцев ключей. Не ждать изменения поведения установки.","Audit installation channels and key owners now. Do not wait for installation behavior to change.","Auditar ahora los canales de instalación y los dueños de las claves. No esperar a que cambie el comportamiento del sistema.","Auditar agora os canais de instalação e os donos das chaves. Não esperar o comportamento do sistema mudar."],source:3
},
{
 topic:["Kotlin Multiplatform","Kotlin Multiplatform","Kotlin Multiplatform","Kotlin Multiplatform"],status:["Тестировать","Test","Probar","Testar"],
 title:["Kotlin 2.4.20-Beta2 остаётся главным KMP-сигналом.","Kotlin 2.4.20-Beta2 remains the main KMP signal.","Kotlin 2.4.20-Beta2 sigue siendo la principal señal para KMP.","Kotlin 2.4.20-Beta2 continua sendo o principal sinal para KMP."],
 lead:["Нового stable-релиза нет, поэтому рекомендация не меняется: измерять в отдельной ветке.","There is no new stable release, so the recommendation stays the same: measure it in an isolated branch.","No hay una nueva versión estable, así que la recomendación no cambia: medirla en una rama aislada.","Não há uma nova versão estável, então a recomendação continua: medir em uma branch isolada."],
 meta:[["Beta","Тестировать","Swift export · сборка","Средний"],["Beta","Test","Swift export · builds","Medium"],["Beta","Probar","Swift export · compilación","Medio"],["Beta","Testar","Swift export · build","Médio"]],
 confirmed:["Beta2 включает incremental compilation для klib по умолчанию, Swift export sealed-иерархий, cross-language inheritance и экспериментальный native image компилятора.","Beta2 enables incremental klib compilation by default, adds Swift export for sealed hierarchies and cross-language inheritance, and introduces an experimental compiler native image.","Beta2 activa por defecto la compilación incremental de klib, añade exportación a Swift de jerarquías sealed, herencia entre lenguajes y una imagen nativa experimental del compilador.","A Beta2 ativa por padrão a compilação incremental de klib, adiciona exportação para Swift de hierarquias sealed, herança entre linguagens e uma imagem nativa experimental do compilador."],
 body:[["Проверять clean и incremental build, XCFramework export, naming, coroutines на Swift-границе, KSP, serialization и Compose compiler compatibility.","Отсутствие stable-релиза — полезная информация: production-план не должен зависеть от beta."],["Test clean and incremental builds, XCFramework export, naming, coroutines across the Swift boundary, KSP, serialization, and Compose compiler compatibility.","The lack of a stable release is useful information: production planning should not depend on the beta."],["Conviene probar builds limpias e incrementales, exportación de XCFramework, nombres, coroutines en la frontera con Swift, KSP, serialización y compatibilidad con Compose compiler.","La ausencia de una versión estable es una señal útil: producción no debe depender de la beta."],["Vale testar builds limpas e incrementais, exportação de XCFramework, naming, coroutines na fronteira com Swift, KSP, serialização e compatibilidade com Compose compiler.","A ausência de uma versão estável é um sinal útil: produção não deve depender da beta."]],
 analysis:["Ценность beta — в проверке будущей формы Swift API и времени сборки, а не в раннем production-переходе.","The beta is valuable for testing the future Swift API shape and build performance, not for an early production migration.","La beta sirve para evaluar la futura forma del API Swift y los tiempos de compilación, no para migrar producción antes de tiempo.","A beta serve para avaliar a futura forma da API Swift e o tempo de build, não para migrar produção cedo."],
 migration:[["Изолированная ветка","Средние","Production-риск","Высокий"],["Isolated branch","Medium","Production risk","High"],["Rama aislada","Medio","Riesgo en producción","Alto"],["Branch isolada","Médio","Risco em produção","Alto"]],
 verdict:["Продолжать тестирование, но не переводить production KMP-проект на Beta2.","Keep testing, but do not move a production KMP project to Beta2.","Seguir probando, pero no llevar un proyecto KMP de producción a Beta2.","Continuar testando, mas não migrar um projeto KMP de produção para a Beta2."],source:4
},
{
 topic:["Compose Multiplatform","Compose Multiplatform","Compose Multiplatform","Compose Multiplatform"],status:["Без действий","No action","Sin acción","Sem ação"],
 title:["Compose Multiplatform сохраняет стабильную базу без срочной миграции.","Compose Multiplatform keeps a stable baseline without an urgent migration.","Compose Multiplatform mantiene una base estable sin migración urgente.","Compose Multiplatform mantém uma base estável sem migração urgente."],
 lead:["Если проект уже на 1.11.x и не встречает конкретной ошибки, новая инициатива не нужна.","If a project is already on 1.11.x without a concrete defect, it does not need a new initiative.","Si el proyecto ya está en 1.11.x y no tiene un defecto concreto, no necesita una iniciativa nueva.","Se o projeto já está na 1.11.x e não enfrenta um defeito concreto, não precisa de uma nova iniciativa."],
 meta:[["Stable baseline","Без действий","Планирование","Низкий"],["Stable baseline","No action","Planning","Low"],["Base estable","Sin acción","Planificación","Bajo"],["Base estável","Sem ação","Planejamento","Baixo"]],
 confirmed:["Актуальной stable-линией остаётся Compose Multiplatform 1.11.x; iOS parallel rendering включён по умолчанию, Apple x86_64 больше не поддерживается, web target остаётся beta.","Compose Multiplatform 1.11.x remains the stable line; iOS parallel rendering is enabled by default, Apple x86_64 support is gone, and the web target remains beta.","Compose Multiplatform 1.11.x sigue siendo la línea estable; el rendering paralelo en iOS está activo por defecto, Apple x86_64 ya no se admite y web sigue en beta.","Compose Multiplatform 1.11.x continua sendo a linha estável; o rendering paralelo no iOS vem ativo por padrão, Apple x86_64 não é mais suportado e web continua em beta."],
 body:[["Продолжать проверять iOS rendering, text input, accessibility и platform interop.","Для CI и симуляторов нормой должны стать Apple Silicon targets."],["Continue checking iOS rendering, text input, accessibility, and platform interop.","Apple Silicon targets should be the default for CI and simulators."],["Hay que seguir verificando rendering en iOS, entrada de texto, accesibilidad e interoperabilidad.","Los targets Apple Silicon deberían ser la opción normal para CI y simuladores."],["Continuar verificando rendering no iOS, entrada de texto, acessibilidade e interoperabilidade.","Targets Apple Silicon devem ser o padrão para CI e simuladores."]],
 analysis:["Отсутствие крупного релиза не означает отсутствие работы: стабильность поддерживается целевыми тестами, а не постоянной сменой версий.","No major release does not mean no engineering: stability comes from targeted tests, not constant version churn.","Que no haya un gran lanzamiento no significa que no haya trabajo: la estabilidad depende de pruebas dirigidas, no de cambiar versiones sin parar.","A ausência de um grande lançamento não significa ausência de trabalho: estabilidade vem de testes direcionados, não de trocar versões sem parar."],
 migration:[["Изменения кода","Нет","Приоритет","Низкий"],["Code changes","None","Priority","Low"],["Cambios de código","Ninguno","Prioridad","Baja"],["Mudanças de código","Nenhuma","Prioridade","Baixa"]],
 verdict:["Оставаться на stable и обновляться ради конкретной выгоды или исправления.","Stay on stable and upgrade for a concrete benefit or fix.","Mantenerse en stable y actualizar por un beneficio o una corrección concreta.","Permanecer na stable e atualizar por um benefício ou uma correção concreta."],source:5
},
{
 topic:["React Native","React Native","React Native","React Native"],status:["Без действий","No action","Sin acción","Sem ação"],
 title:["React Native 0.86 остаётся актуальной stable-версией.","React Native 0.86 remains the relevant stable release.","React Native 0.86 sigue siendo la versión estable relevante.","React Native 0.86 continua sendo a versão estável relevante."],
 lead:["Если проект уже обновлён, на этой неделе отдельной работы нет.","If the project is already current, there is no separate initiative this week.","Si el proyecto ya está actualizado, no hay una iniciativa nueva esta semana.","Se o projeto já está atualizado, não há uma iniciativa separada nesta semana."],
 meta:[["Stable baseline","По необходимости","Android UI · delivery","Низкий"],["Stable baseline","As needed","Android UI · delivery","Low"],["Base estable","Según necesidad","UI Android · entrega","Bajo"],["Base estável","Conforme necessidade","UI Android · entrega","Baixo"]],
 confirmed:["0.86 остаётся стабильной базой с улучшенной edge-to-edge поддержкой Android 15+ и DevTools без заявленных user-facing breaking changes.","0.86 remains the stable baseline with improved Android 15+ edge-to-edge support and DevTools, without declared user-facing breaking changes.","0.86 sigue siendo la base estable con mejor soporte edge-to-edge en Android 15+ y mejoras de DevTools, sin breaking changes visibles declarados.","0.86 continua sendo a base estável, com melhor suporte edge-to-edge no Android 15+ e melhorias no DevTools, sem breaking changes visíveis declarados."],
 body:[["Обновление особенно оправдано при старых workaround для insets, keyboard, modals, fullscreen layout и navigation bar styling.","Проект на 0.86 не требует работы ради самого факта еженедельного дайджеста."],["The upgrade is most useful where older workarounds exist for insets, keyboard, modals, fullscreen layout, or navigation bar styling.","A project already on 0.86 does not need manufactured work for a weekly digest."],["La actualización es especialmente útil cuando existen workarounds para insets, teclado, modales, fullscreen o la barra de navegación.","Un proyecto que ya está en 0.86 no necesita trabajo inventado para llenar un resumen semanal."],["A atualização é mais útil quando existem workarounds para insets, teclado, modais, fullscreen ou barra de navegação.","Um projeto que já está na 0.86 não precisa de trabalho inventado para preencher um resumo semanal."]],
 analysis:["Хороший технический обзор должен уметь рекомендовать ничего не делать.","A good technical brief must be able to recommend doing nothing.","Un buen informe técnico también debe saber recomendar no hacer nada.","Um bom informe técnico também precisa saber recomendar não fazer nada."],
 migration:[["Изменения кода","Нет на 0.86","Приоритет","Низкий"],["Code changes","None on 0.86","Priority","Low"],["Cambios de código","Ninguno en 0.86","Prioridad","Baja"],["Mudanças de código","Nenhuma na 0.86","Prioridade","Baixa"]],
 verdict:["Если проект на 0.86 — ничего не делать. Старые версии обновлять при наличии Android UI workaround.","If the project is on 0.86, do nothing. Upgrade older versions when Android UI workarounds justify it.","Si el proyecto está en 0.86, no hacer nada. Actualizar versiones anteriores cuando los workarounds de UI Android lo justifiquen.","Se o projeto está na 0.86, não fazer nada. Atualizar versões anteriores quando os workarounds de UI Android justificarem."],source:6
},
{
 topic:["Ktor","Ktor","Ktor","Ktor"],status:["Обычное обслуживание","Routine","Mantenimiento","Manutenção"],
 title:["Ktor не принёс нового изменения, требующего архитектурной реакции.","Ktor brings no new change that calls for an architectural reaction.","Ktor no trae un cambio nuevo que exija una reacción arquitectónica.","Ktor não traz uma mudança nova que exija reação arquitetural."],
 lead:["Stable 3.5.1 остаётся рабочей базой для mobile clients и Kotlin backend.","Stable 3.5.1 remains the working baseline for mobile clients and Kotlin backends.","La versión estable 3.5.1 sigue siendo la base de trabajo para clientes móviles y backends Kotlin.","A versão estável 3.5.1 continua sendo a base para clientes mobile e backends Kotlin."],
 meta:[["Stable baseline","Обслуживать","Сеть · backend","Низкий"],["Stable baseline","Maintain","Networking · backend","Low"],["Base estable","Mantener","Red · backend","Bajo"],["Base estável","Manter","Rede · backend","Baixo"]],
 confirmed:["Ktor 3.5.1 остаётся актуальной стабильной версией с исправлениями совместимости Kotlin 2.4, HTTP, caching, authentication, WebRTC и platform engines.","Ktor 3.5.1 remains the current stable release with fixes across Kotlin 2.4 compatibility, HTTP, caching, authentication, WebRTC, and platform engines.","Ktor 3.5.1 sigue siendo la versión estable actual, con correcciones de compatibilidad con Kotlin 2.4, HTTP, caché, autenticación, WebRTC y engines de plataforma.","Ktor 3.5.1 continua sendo a versão estável atual, com correções de compatibilidade com Kotlin 2.4, HTTP, cache, autenticação, WebRTC e engines de plataforma."],
 body:[["Если обновление ещё не выполнено, проверить auth retries, cache-control, redirects, cancellation, uploads, WebSockets, TLS, Darwin background/resume и mapping ошибок.","Dependency upgrade должен оставаться наблюдаемым и откатываемым, поэтому его не стоит смешивать с refactoring auth или networking."],["If the upgrade is pending, verify auth retries, cache control, redirects, cancellation, uploads, WebSockets, TLS, Darwin background/resume, and error mapping.","Keep the dependency upgrade observable and reversible; do not combine it with an auth or networking refactor."],["Si la actualización está pendiente, revisar reintentos de auth, caché, redirects, cancelación, uploads, WebSockets, TLS, background/resume en Darwin y mapeo de errores.","La actualización debe ser observable y reversible; no conviene mezclarla con un refactor de auth o networking."],["Se a atualização está pendente, revisar retries de auth, cache, redirects, cancelamento, uploads, WebSockets, TLS, background/resume no Darwin e mapeamento de erros.","A atualização deve ser observável e reversível; não vale misturá-la com refatoração de auth ou networking."]],
 analysis:["Неделя без нового backend-релиза снижает риск совмещённой миграции Kotlin/Ktor и позволяет разделить изменения.","A week without a new backend release lowers the pressure for a combined Kotlin/Ktor migration and makes it easier to separate changes.","Una semana sin un nuevo release de backend reduce la presión de una migración combinada Kotlin/Ktor y permite separar cambios.","Uma semana sem um novo release de backend reduz a pressão por uma migração combinada Kotlin/Ktor e ajuda a separar mudanças."],
 migration:[["Patch upgrade","Низкие","Сетевой риск","Средний"],["Patch upgrade","Low","Networking risk","Medium"],["Actualización patch","Baja","Riesgo de red","Medio"],["Atualização patch","Baixa","Risco de rede","Médio"]],
 verdict:["Если проект уже на 3.5.1 — действий нет. Иначе обновить отдельно от сетевого рефакторинга.","If the project is already on 3.5.1, take no action. Otherwise upgrade separately from networking refactors.","Si el proyecto ya está en 3.5.1, no hay acción. Si no, actualizar por separado de cualquier refactor de red.","Se o projeto já está na 3.5.1, não há ação. Caso contrário, atualizar separadamente de qualquer refatoração de rede."],source:7
}
];
